# Generated by Django 3.1.1 on 2021-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('typrs', models.SmallIntegerField(default=10, verbose_name='展现位置')),
                ('img', models.ImageField(max_length=255, upload_to='%Y%m/slider', verbose_name='图片地址')),
                ('reorder', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序字段')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('target_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标地址')),
            ],
            options={
                'verbose_name': '系统表',
                'verbose_name_plural': '系统表',
                'db_table': 'system_slider',
                'ordering': ['-reorder'],
            },
        ),
    ]
