# Generated by Django 3.1.1 on 2021-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('main_img', models.ImageField(max_length=256, upload_to='%Y%m/sight/', verbose_name='主图')),
                ('banner_img', models.ImageField(max_length=256, upload_to='%Y%m/sight/', verbose_name='详情主图')),
                ('content', models.TextField(blank=True, null=True, verbose_name='详细')),
                ('score', models.FloatField(default=5, verbose_name='评分')),
                ('province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='城市')),
                ('area', models.CharField(blank=True, max_length=32, null=True, verbose_name='区/县')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='乡镇')),
                ('min_price', models.FloatField(default=0, verbose_name='最低价格')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否精选')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '景点信息表',
                'verbose_name_plural': '景点信息表',
                'db_table': 'sight',
                'ordering': ['-updated_at'],
            },
        ),
    ]
