# Generated by Django 3.1.1 on 2021-01-31 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=2, verbose_name='性别')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('is_email_valid', models.BooleanField(default=False, verbose_name='邮箱验证')),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('is_phone_valid', models.BooleanField(default=False, verbose_name='手机号验证')),
                ('source', models.CharField(blank=True, max_length=16, null=True, verbose_name='登录来源')),
                ('version', models.CharField(blank=True, max_length=16, null=True, verbose_name='版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户详情表',
                'verbose_name_plural': '用户详情表',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('source', models.CharField(blank=True, max_length=16, null=True, verbose_name='登录来源')),
                ('version', models.CharField(blank=True, max_length=16, null=True, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_record', to='accounts.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户日志表',
                'verbose_name_plural': '用户日志表',
                'db_table': 'login_record',
            },
        ),
    ]
